'use strict';
const F=window.FF;
F.load=async()=>{try{if(F.guest())F.s.projects=F.local().sort((a,b)=>new Date(b.updated_at)-new Date(a.updated_at));else{const{data,error}=await F.db.from('frameflow_projects').select('*').order('updated_at',{ascending:false});if(error)throw error;F.s.projects=data||[]}}catch(e){console.error(e);F.toast('Nuvem indisponível; usando modo local.',true);F.s.guest=true;F.s.projects=F.local()}};
F.create=async()=>{let p={id:F.uid(),name:'Projeto sem título',document:F.blank(),created_at:new Date().toISOString(),updated_at:new Date().toISOString()};try{if(F.guest()){const a=F.local();a.unshift(p);F.setLocal(a)}else{const{data,error}=await F.db.from('frameflow_projects').insert({owner_id:F.s.user.id,name:p.name,document:p.document}).select().single();if(error)throw error;p=data}F.s.active=p;F.s.doc=F.clone(p.document);F.s.history=[];F.s.future=[];F.s.selected=null;F.s.panel=null;F.s.view='editor';F.render()}catch(e){F.toast(e.message||'Erro ao criar',true)}};
F.open=id=>{const p=F.s.projects.find(x=>x.id===id);if(!p)return;F.s.active=F.clone(p);F.s.doc=F.clone(p.document||F.blank());F.s.history=[];F.s.future=[];F.s.selected=null;F.s.panel=null;F.s.view='editor';F.render()};
F.delProject=async id=>{try{if(F.guest())F.setLocal(F.local().filter(p=>p.id!==id));else{const{error}=await F.db.from('frameflow_projects').delete().eq('id',id);if(error)throw error}F.s.menu=null;await F.load();F.render();F.toast('Projeto excluído')}catch(e){F.toast(e.message,true)}};
F.dupProject=async id=>{const x=F.s.projects.find(p=>p.id===id);if(!x)return;let p={id:F.uid(),name:`${x.name} — cópia`,document:F.clone(x.document),created_at:new Date().toISOString(),updated_at:new Date().toISOString()};try{if(F.guest()){const a=F.local();a.unshift(p);F.setLocal(a)}else{const{error}=await F.db.from('frameflow_projects').insert({owner_id:F.s.user.id,name:p.name,document:p.document});if(error)throw error}F.s.menu=null;await F.load();F.render();F.toast('Projeto duplicado')}catch(e){F.toast(e.message,true)}};
F.queueSave=()=>{F.s.saveState='Salvando…';document.querySelector('.save-state')?.replaceChildren('Salvando…');clearTimeout(F.st);F.st=setTimeout(F.save,650)};
F.save=async()=>{if(!F.s.active)return;F.s.active.document=F.clone(F.s.doc);F.s.active.updated_at=new Date().toISOString();try{if(F.guest()){const a=F.local(),i=a.findIndex(p=>p.id===F.s.active.id);i>=0?a[i]=F.clone(F.s.active):a.unshift(F.clone(F.s.active));F.setLocal(a)}else{const{error}=await F.db.from('frameflow_projects').update({name:F.s.active.name,document:F.s.doc}).eq('id',F.s.active.id);if(error)throw error}F.s.saveState='Salvo'}catch(e){F.s.saveState='Erro ao salvar';console.error(e)}document.querySelector('.save-state')?.replaceChildren(F.s.saveState)};
