'use strict';
window.FF={};
const F=window.FF;
const cfg=window.FRAMEFLOW_CONFIG||{};
F.db=window.supabase?.createClient(cfg.supabaseUrl||'',cfg.supabasePublishableKey||'');
F.app=document.getElementById('app');
F.imageInput=document.getElementById('imageInput');
F.blank=()=>({version:1,canvas:{width:390,height:844,background:'#ffffff'},layers:[]});
F.s={view:'boot',authMode:'login',user:null,guest:false,projects:[],search:'',active:null,doc:F.blank(),selected:null,tool:'select',panel:null,zoom:.62,panX:0,panY:0,history:[],future:[],saveState:'Salvo',drag:null,pinch:new Map(),menu:null};
F.uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
F.clone=o=>JSON.parse(JSON.stringify(o));
F.esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
F.icon=(n,z=20)=>`<i data-lucide="${n}" style="width:${z}px;height:${z}px"></i>`;
F.refresh=()=>{try{window.lucide?.createIcons({attrs:{'stroke-width':1.9}})}catch(_){}};
F.toast=(m,err=false)=>{const h=document.getElementById('toastHost');h.innerHTML=`<div class="toast ${err?'error':''}">${F.esc(m)}</div>`;clearTimeout(F.tt);F.tt=setTimeout(()=>h.innerHTML='',2700)};
F.guest=()=>F.s.guest||!F.s.user;
F.local=()=>{try{return JSON.parse(localStorage.getItem('frameflow_projects')||'[]')}catch(_){return[]}};
F.setLocal=x=>localStorage.setItem('frameflow_projects',JSON.stringify(x));
F.date=d=>{try{return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(d))}catch(_){return'agora'}};
F.render=()=>{if(F.s.view==='auth')F.auth();else if(F.s.view==='dashboard')F.dashboard();else if(F.s.view==='editor')F.editor();else F.app.innerHTML=`<div class="auth-view"><div class="brand"><div class="brand-mark">${F.icon('frames',26)}</div><div><h1>FrameFlow</h1><p>Carregando…</p></div></div></div>`;F.refresh()};
F.auth=()=>{F.app.innerHTML=`<main class="auth-view view"><section class="auth-shell"><div class="brand"><div class="brand-mark">${F.icon('frames',26)}</div><div><h1>FrameFlow Mobile</h1><p>Design profissional direto no celular</p></div></div><div class="auth-card"><h2>${F.s.authMode==='login'?'Bem-vindo de volta':'Crie seu workspace'}</h2><p>${F.s.authMode==='login'?'Entre para continuar seus projetos salvos.':'Sua conta sincroniza projetos entre dispositivos.'}</p><div class="auth-tabs"><button class="auth-tab ${F.s.authMode==='login'?'active':''}" data-action="auth-tab" data-mode="login">Entrar</button><button class="auth-tab ${F.s.authMode==='signup'?'active':''}" data-action="auth-tab" data-mode="signup">Criar conta</button></div><form id="authForm" class="auth-form"><div class="auth-row"><label>E-mail</label><input id="email" class="input" type="email" autocomplete="email" required placeholder="voce@email.com"></div><div class="auth-row"><label>Senha</label><input id="password" class="input" type="password" minlength="6" required placeholder="Mínimo de 6 caracteres"></div><button class="primary-btn full">${F.s.authMode==='login'?'Entrar':'Criar minha conta'}</button></form><div class="auth-divider">ou</div><button class="secondary-btn full" data-action="guest">${F.icon('smartphone',18)}&nbsp; Continuar como convidado</button><div class="tiny-note">No modo convidado, os arquivos ficam neste aparelho. Com conta, o autosave usa Supabase protegido por usuário.</div></div></section></main>`};
